spring:
  application:
    name: kafka-demo
  sleuth:
    propagation-keys:
      - x-correlation-id
      - x-session-id
  cloud:
    stream:
      bindings:
        input:
          destination: kafka-demo-topic
          group: kafka-demo-group
          content-type: application/json
      kafka:
        bindings:
          input:
            consumer:
              enableDlq: true
              dlqName: kafka-demo-topic-dlq
              autoCommitOnError: true
              ackEachRecord: true
              configuration:
                max.poll.interval.ms: 90000
        binder:
          zkNodes: localhost:2181
          brokers: localhost:9092
          auto-create-topics: true
          replicationFactor: 1
  jpa:
    hibernate:
      ddl-auto: none
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          query:
            plan_cache_max_size: 2048
            plan_parameter_metadata_max_size: 32
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dollardb
    username: postgres
    password: postgres1234
  main:
    allow-bean-definition-overriding: true